### ISSUE TITLE
Problem with void interface crafting

### ISSUE THREAD

**Issue by sync777** [TheNimbleNinja/project-equivlandce-2#5]
Problem with void interface crafting.
In order to craft void interface, a crafting chain is required, as a result of which crafting is required on arcane forge, and there mana is required, which is added through void interface/
![Безымянный](https://user-images.githubusercontent.com/73545355/136957372-f689cf84-bbf7-4b58-8630-ad02ecdf384c.png)

**Comment by TheNimbleNinja** [comment]
im pretty sure the arcane stone can be made without the lens
but i didnt relize that i did this

**Comment by sync777** [comment]
> im pretty sure the arcane stone can be made without the lens but i didnt relize that i did this

please tell me how to make it

**Comment by TheNimbleNinja** [comment]
you scavenge the crystals and can make the arcane stone i think

**Comment by TheNimbleNinja** [comment]
i should of fixed this in latest update hopefully
