### ISSUE TITLE
can't make terrasteel

### ISSUE THREAD

**Issue by tiankong-sky** [TheNimbleNinja/project-equivlandce-2#6]
![1](https://user-images.githubusercontent.com/85264564/138249566-92c50342-9fef-477d-a103-8e7e9dc85cef.png)
![2](https://user-images.githubusercontent.com/85264564/138249577-6dc0328f-18b4-4feb-a8ac-428586ae7e6b.png)
![3](https://user-images.githubusercontent.com/85264564/138249580-37101e99-2c40-40ad-9ac0-1bb1167f7eb2.png)
![4](https://user-images.githubusercontent.com/85264564/138249584-ed4bc122-6b75-4f39-acca-51f5b14aecb6.png)
![5](https://user-images.githubusercontent.com/85264564/138249590-5366d984-70fd-4b04-9148-22a9cda04f07.png)
![6](https://user-images.githubusercontent.com/85264564/138249592-e9a47266-b940-4e0e-80bf-a0233d150341.png)
![7](https://user-images.githubusercontent.com/85264564/138249595-01a0cdd4-2549-44b5-8cf7-d6ff6dabdafb.png)
![8](https://user-images.githubusercontent.com/85264564/138249597-ed150366-9923-4f12-b95c-2cbc8ca36d40.png)
![9](https://user-images.githubusercontent.com/85264564/138249599-8e39c44e-8dd7-402d-930c-b4605e67323d.png)
![10](https://user-images.githubusercontent.com/85264564/138249606-857a36d3-0096-47cd-8bca-19c9b6eba329.png)
![11](https://user-images.githubusercontent.com/85264564/138249612-e64c3143-5547-40f6-8771-9c4337b25de1.png)

**Comment by TheNimbleNinja** [comment]
OOF

**Comment by tiankong-sky** [comment]
then I can't get thaumcraft because it need blood magic
and the oil need that ipad the ipad need Plastic, the plastic need oil...

**Comment by TheNimbleNinja** [comment]
thaumcraft doesnt need blood magic to get into from wat i remember
you dont need the ipad to get oil.
 im also working on  the pack some more  already fixed the issue with blood magic

**Comment by TheNimbleNinja** [comment]
okay i added a recipe for turning bitinum into oil
and added it to granite excavating

**Comment by TheNimbleNinja** [comment]
hopefully fixed this issue
