### ISSUE TITLE
craft contention

### ISSUE THREAD

**Issue by tiankong-sky** [TheNimbleNinja/project-equivlandce-2#7]
![1](https://user-images.githubusercontent.com/85264564/138837292-881fbc2b-8ee1-4133-b9dc-30fb39c84f9f.png)
Silicon
![2](https://user-images.githubusercontent.com/85264564/138837301-02c2cf28-200c-41f5-8ce5-f7d29111f6d7.png)
![3](https://user-images.githubusercontent.com/85264564/138837306-a08c39b7-e5ba-4231-b466-6e700bde2e76.png)
Amethyst

**Comment by TheNimbleNinja** [comment]
should of fixed this
